import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";



export default function ReportViewer({ report }) {
    return (
        <div className="bg-white rounded-xl shadow-lg h-full overflow-hidden">

            {/* Header */}

            <div className="border-b p-5">

                <h2 className="text-2xl font-bold text-gray-800">
                    📄 Research Report
                </h2>

                <p className="text-gray-500 mt-1">
                    Generated by the Multi-Agent Research System
                </p>

            </div>

            {/* Report */}

            <div className="overflow-auto h-[calc(100vh-240px)] p-8">

                <article className="prose prose-lg max-w-none">

                    <ReactMarkdown remarkPlugins={[remarkGfm]}>
                        {report}
                    </ReactMarkdown>

                </article>

            </div>

        </div>
    );
}

